name: Build Test Deploy CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_unit_test:

    runs-on: ubuntu-latest   

    steps:
    - name: Display SoftUni username
      run: echo "milagg"
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies    
      run: npm install
    - name: Start the app
      run: npm start &
    - name: Run unit tests
      run: npm run test:unit

  ui_tests:

    runs-on: ubuntu-latest
    needs: build_unit_test

    steps:
    - name: Checkout repository 
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install    
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Start the app
      run: npm start &  
    - name: Run UI tests
      run: npm run test:ui    
    
